US016 edit capability
Cormac-F/infinite-harmony-ui pull request #17
Opened 2024-01-10 16:27 UTC by caitlinbulloch

**Edit a Capability Name**

- created capability controller
- created capability service
- created capability model
- created capability list, edit, and confirm html pages. 

<img width="1247" alt="Screenshot 2024-01-10 at 16 24 31" src="https://github.com/Cormac-F/infinite-harmony-ui/assets/145448951/28df1a60-6d28-4007-82a4-1df9d1c0b60b">

<img width="855" alt="Screenshot 2024-01-10 at 16 25 05" src="https://github.com/Cormac-F/infinite-harmony-ui/assets/145448951/e3636d87-048f-4c0e-8267-0baea59b1377">

<img width="761" alt="Screenshot 2024-01-10 at 16 25 13" src="https://github.com/Cormac-F/infinite-harmony-ui/assets/145448951/419dbfea-ed88-4c21-bdb4-3602797e276e">

2024-01-10 16:41 UTC, eoinmcbennett requested changes
Looks great, can you just take a look at some of the things I flagged.

2024-01-10 16:41 UTC, eoinmcbennett commented on app.ts
> +app.use(session({ secret: "NOT HARDCODED SECRET", cookie: { maxAge: 60000 }}));
Watch for this in a merge conflict, use the config value for this.

2024-01-10 16:41 UTC, eoinmcbennett commented on controller/capabilityController.ts
> +    })
Does this ever get used?

2024-01-10 16:41 UTC, eoinmcbennett commented on service/capabilityService.ts
> +        const response = await axios.get("http://localhost:8080/api/capability");
This url will need to be changed to use the env API_URL or it wont work with AWS backend.

2024-01-10 16:41 UTC, eoinmcbennett commented on service/capabilityService.ts
> +        const response = await axios.get("http://localhost:8080/api/capability/" + id);
This url will need to be changed to use the env API_URL or it wont work with AWS backend.

2024-01-10 16:41 UTC, eoinmcbennett commented on service/capabilityService.ts
> +        const response = await axios.put("http://localhost:8080/api/capability/" + capability.capabilityID , capability)
This url will need to be changed to use the env API_URL or it wont work with AWS backend.

2024-01-11 09:07 UTC, eoinmcbennett approved these changes

2024-01-11 11:10 UTC, eoinmcbennett requested changes

2024-01-11 11:10 UTC, eoinmcbennett commented on app.ts
> +
Having multiple of these can break things, consolidate them into one.

2024-01-11 11:10 UTC, eoinmcbennett commented on app.ts
>  }
Having multiple of these can break things, consolidate them into one.

2024-01-11 12:04 UTC, eoinmcbennett requested changes

2024-01-11 12:04 UTC, eoinmcbennett commented on app.ts
Dont do app.use(session) twice, could break things.

2024-01-11 13:45 UTC, eoinmcbennett approved these changes

2024-01-11 14:20 UTC, Cormac-F approved these changes

2024-01-11 14:22 UTC, merged