US001-view-job-roles
Cormac-F/infinite-harmony-ui pull request #6
Opened 2023-12-07 11:28 UTC by Cormac-F

- Created jobService, jobController, Job and view-job files. 
- Shows a list of Job IDs and Job Names.

<img width="1433" alt="Screenshot 2023-12-07 at 11 25 26 am" src="https://github.com/Cormac-F/infinite-harmony-ui/assets/145451997/9f6a03a3-2695-4b36-a537-c7f924e0ce4a">

2023-12-07 13:42 UTC, jkelso662 commented on views/list-jobs.html
> +                <img src="../public/images/kainos-logo.png" alt="Kainos Logo" width="100" height="30">
Doesn't look like this is correctly referenced based on the screenshot on the ticket description. Also there is no `kainos-logo.png` image in this PR.

2023-12-07 13:44 UTC, jkelso662 requested changes
Nice! Looks good but I think you have a missing image resulting in a broken image href. Fix that and this PR should be good :)

2023-12-12 10:28 UTC, CharlesM988 commented
Some changes to the styling of view-jobs.html.

- Modified view-jobs.html to include bootstrap styling inline with the rest of the pages
- Created styles.css and added styles

<img width="846" alt="Screenshot 2023-12-12 at 10 26 31" src="https://github.com/Cormac-F/infinite-harmony-ui/assets/145450764/4be20ff0-892e-412c-985f-874e1420a7bf">

2023-12-12 14:02 UTC, amchugh689 approved these changes
LGTM!

2023-12-14 09:13 UTC, CharlesM988 approved these changes
The issues with the logo were resolved. This should be merged now.

2023-12-14 10:37 UTC, jkelso662 approved these changes
Best to update the screenshot in the description with the fixed UI but I'll take your word for it that the image is fixed 😄

2023-12-14 11:02 UTC, merged